[package]
name = "minimeshb"
version = "0.1.0"
edition = "2024"
links = "minimeshb"

[dependencies]
env_logger = "0.11.3"
log = "0.4.21"
tempfile = "3.8.0"
libmeshb-sys = {git = "https://github.com/tucanos/libmeshb-sys.git", optional = true, tag = "0.1.0"}
rand = "0.9.0"

